export const ELabels = {
  newUser: 'New user?',
  createAccount: 'Create an account',
  forgotPassword: 'Forgot password?',
  login: 'Log in',
  signUp: 'Sign Up',
  or: 'OR',
  search: 'Search',
  aboutUs: 'About us',
  contactUs: 'Contact us',
  searchTeachers: 'Search teachers',
  jobSearch: 'Job Search',
  appUrl: 'teachersdirectory.co.uk',
  location: 'Location',
  searchRadius: 'Search radius',
  firstName: 'First name',
  surname: 'Surname',
  email: 'Email address',
  password: 'Password',
} as const
