version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    ports:
      - '3000:3000'
    image: teachers_directory

  db:
    container_name: teachers_directory_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - '5432:5432'

volumes:
  postgres-db:
    driver: local
