export enum EScreenId {
  HOME = 'HOME',
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  SIGN_UP_TEACHER = 'SIGN_UP_TEACHER',
  SIGN_UP_SCHOOL = 'SIGN_UP_SCHOOL',
  SIGN_UP_ACCOUNT_TYPE = 'SIGN_UP_ACCOUNT_TYPE',
  SEARCH = 'SEARCH',
}

