import { type AppType } from 'next/app'

import { api } from '~/utils/api'

import '~/styles/globals.css'
import { Public_Sans } from 'next/font/google'
import Head from 'next/head'
const publicSans = Public_Sans({ subsets: ['latin'] })

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Teachers Directory</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={publicSans.className}>
        <Component {...pageProps} />
      </div>
    </>
  )
}

export default api.withTRPC(MyApp)
